### ISSUE TITLE
BrokenPipeError: [Errno 32] Broken pipe

### ISSUE THREAD

**Issue by HarryWu-CHN** [MuMiN-dataset/mumin-build#13]
When parsing articles, it keep getting `BrokenPipeError: [Errno 32] Broken pipe`, and the process was terminated.

<details>
  <summary>Error message</summary>

![image](https://user-images.githubusercontent.com/63134210/180337870-722653c7-fc2e-44fe-8678-40bd7a4e307f.png)

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/local/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.8/multiprocessing/pool.py", line 136, in worker
    put((job, i, (False, wrapped)))
  File "/usr/local/lib/python3.8/multiprocessing/queues.py", line 368, in put
    self._writer.send_bytes(obj)
  File "/usr/local/lib/python3.8/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/local/lib/python3.8/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header)
  File "/usr/local/lib/python3.8/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
```
</details>

Rehydrating is really time-consuming, above process ran for more than 15 hours. So I really wish adding a checkpoint after rehydrating. Thanks.

+ OS: Ubuntu 18.04
+ Python: 3.8.10

**Comment by saattrupdan** [comment]
Fixed in https://github.com/MuMiN-dataset/mumin-build/releases/tag/v1.9.0, closing. Please open a new issue if the problem (or others) persist 🙂
